name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -PuseCommitHashInVersion
      - name: Build with Gradle(nomixin)
        run: ./gradlew build -PuseCommitHashInVersion -Pnomixin
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Quit-1.8.9
          path: build/libs